[theme]
base = "light"
primaryColor = "#FF4B4B"
backgroundColor = "#E6F8FF"
secondaryBackgroundColor = "#699EDE"
textColor = "#31333F"
font = "sans serif"

[layout]
wide = true

[server]
headless = true
enableCORS = false
enableWebsocketCompression = true
server.maxUploadSize = 200
runOnSave = false
server.threaded = true
maxUploadSize = 100
threaded = true

[logger]
level = "error"
